version: "3"
services:
  app:
    build: ./docker/php-fpm
    volumes:
      - ${PROJECT_PATH}:/var/www/app
      - ./logs:/var/log/php
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/app
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    build: ./docker/nginx
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/var/www/app
      - ./logs:/var/log/nginx

  mysql:
    build: ./docker/mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  db-data:
    driver: local